name: medicare
description: "Una aplicaci√≥n para doctores y pacientes"

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  get: ^4.7.2
  google_maps_flutter: ^2.12.1
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  flutter_lucide: ^1.6.2
  flutter_reorderable_grid_view: ^5.5.0
  timelines: ^0.1.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  carousel_slider: ^5.0.0
  syncfusion_flutter_core: ^29.1.35
  syncfusion_flutter_sliders: ^29.1.35
  file_picker: ^10.1.5
  syncfusion_flutter_charts: ^29.1.35
  animate_gradient: ^0.0.3
  syncfusion_flutter_calendar: ^29.1.35
  multi_select_flutter: ^4.1.3
  flutter_dropzone: ^4.2.1
  http: ^1.4.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  printing: ^5.14.2
  drop_zone: ^1.0.2
  fl_chart: ^1.0.0
  cached_network_image: ^3.4.1
  pdfrx: ^2.1.14
  super_drag_and_drop: ^0.9.1
  super_clipboard: ^0.9.1
  web: ^1.1.1
  flutter_widget_from_html: ^0.17.1

  blix_essentials:
    path: ../blix_essentials


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/logo/
    - assets/data/
    - assets/avatar/
    - assets/images/dummy/
    - assets/images/products/